spring.application.name=backend
server.port=8081
spring.datasource.url=jdbc:postgresql://furia.c5iqg6ygkgid.us-east-2.rds.amazonaws.com:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=24032004
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
firebase.credentials.path=file:///C:/Users/lucas/Documents/firebase/furia-timeline-firebase-adminsdk-fbsvc-93e5cb9e3b.json
hibernate.transaction.jta.platform=org.hibernate.engine.transaction.internal.jta.JtaPlatformBase
spring.jpa.properties.hibernate.transaction.coordinator_class=org.hibernate.transaction.JDBCTransactionFactory
twitter.client-id=MDNyOGpieHJaeHRyNG84LTlKNzQ6MTpjaQ
twitter.client-secret=ELTN5eB4qarqDZ2PbcQNBtq2HzZtoli3Zz6JP58H-BlkRkVFo0
twitter.redirect-uri=http://localhost:8081/login/oauth2/code/twitter
google.credentials.path=C:/Users/lucas/Documents/firebase/valiant-pager-458500-f9-e1ae84095b5c.json
BEARER_TOKEN=AAAAAAAAAAAAAAAAAAAAAPuq0wEAAAAACozqbdNHtNCj1lsjXDkwJEbdp2U%3DFHeNLDYL5FaNL7cLCGDfdlukFtYKl8jMT9Uwi26F3DQ6kBMuWh
jwt.secret=8sD!29#kd*3F$JshfLq@1ZxNwOp7UvTz
